apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: scapinoculars
  name: scapinoculars
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 2112
  selector:
    app: scapinoculars
status:
  loadBalancer: {}
