apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "2112"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: scapinoculars
  name: scapinoculars
spec:
  ports:
  - port: 80
    name: metrics
    protocol: TCP
    targetPort: 2112
  selector:
    app: scapinoculars
status:
  loadBalancer: {}
