apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kube-bench-viewer
  name: kube-bench-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-bench-viewer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-bench-viewer
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
          - name: kube-bench-index
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: kube-bench-index
          configMap:
            name: kubeviewercm
status: {}
